image: node:20

stages:
  - install
  - test
  - lint
  - style
  - build

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run test

lint:
  stage: lint
  script:
    - npm run lint

style:
  stage: style
  script:
    - npm run style

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/